/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

group = "canaryprism"
version = "1.4.1-beta-1"

description = "DiscordBotClient"

java.toolchain.languageVersion = JavaLanguageVersion.of(22)

application {
    mainClass = "canaryprism.dbc.Main"
    mainModule = "canaryprism.dbc"
}


repositories {
    mavenLocal()
    mavenCentral()
}
dependencies {
    implementation(libs.com.formdev.flatlaf)
    implementation(libs.org.apache.commons.commons.text)
    implementation(libs.org.json.json)
    implementation(libs.dev.dirs.directories)
    implementation(libs.com.github.vincentrussell.java.ini.parser)
    implementation(libs.org.javacord.javacord)
    implementation(libs.com.twelvemonkeys.imageio.imageio.webp)

    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
