/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

group = "canaryprism"
version = "1.4.1-beta-1"

description = "DiscordBotClient"

java.toolchain.languageVersion = JavaLanguageVersion.of(22)

application {
    mainClass = "canaryprism.dbc.Main"
//    mainModule = "canaryprism.dbc"
}


repositories {
    mavenLocal()
    mavenCentral()
}
dependencies {
    implementation(libs.flatlaf)
    implementation(libs.commons.text)
    implementation(libs.json)
    implementation(libs.directories)
    implementation(libs.javacord)
    implementation(libs.imageio.webp)
    implementation(libs.caffeine)

    testImplementation(libs.jupiter)
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
